### ISSUE TITLE
is it possible to implement a tensor-train neural network layer using tntorch?

### ISSUE THREAD

**Issue by yiulau** [rballester/tntorch#6]
It is not immediately obvious to me that it can be done just by skimming through the documentation and tutorials. I am trying to replace a fully connected layer in a neural network by a tensor-train format matrix. So I need to be able to train the tensor-train cores by backpropogation and do it on multiple GPU. Any clarifications would be appreciated. Thx.

**Comment by rballester** [comment]
Hi yiulau, so I suppose your forward operation is M times V, where M is a TT matrix and V is a TT vector? In other words, a matvec operation in the TT format?

**Comment by yiulau** [comment]
Yes. More specifically it is a NLP task where the TT matrix would be the compressed embedding matrix and the v would be a one-hot vector performing a lookup.

**Comment by yiulau** [comment]
More specifically I would like to know if the backend implicitly converts the TT matrix back to full tensor form.

**Comment by rballester** [comment]
If v is a one hot vector, the matvec means selecting one row from your matrix, which you can do using the brackets [...]. There is no implicit decompression, in fact decompression only happens if you explicitly call .torch().

By the way, TT matrices are not supported as such, but you can represent and operate on them via standard TT tensors.
